### ISSUE TITLE
Tensorrt Dynamic Height&Width

### ISSUE THREAD

**Issue by col-in-coding** [stochasticai/x-stable-diffusion#13]
Is it possible to build tensorrt engine with dynamic height and width?

**Comment by Toan-Do** [comment]
Yes, you need to do some steps to set the height and width dynamic:

1.  Set dynamic axises for height and width when converting model from pytorch model to onnx
2. Set dynamic shape when converting model from onnx to tensorrt

But as our experiments the height and width do not affect on the speed. You can use smaller num_inference_steps to get faster.

**Comment by col-in-coding** [comment]
> Yes, you need to do some steps to set the height and width dynamically for tensorrt model:
> 
> 1. Set dynamic axises for height and width when converting model from pytorch model to onnx
> 2. Set dynamic shape when converting model from onnx to tensorrt
> 
> But as our experiments the height and width do not affect on the speed. You can use smaller num_inference_steps to get faster.

Thx for your response.
But for my experiment, made height and width changeable from 256 to 512, but only outputs with width 512 were correct.
That is so wired!

**Comment by col-in-coding** [comment]
@Toan-Do I have created a demo based on this issue, would you mind having a look and tell me what's wrong with it
https://github.com/col-in-coding/Tensorrt-CV/blob/master/dynamic_shape_problem.py
