### ISSUE TITLE
Can't run colab notebook

### ISSUE THREAD

**Issue by Andreilys** [stochasticai/x-stable-diffusion#15]
Was trying to run this colab notebook - https://colab.research.google.com/drive/1m3n2n5bfNpRgWJ8K-xwTvhzrTQETWduq?usp=sharing#scrollTo=ONitKUKN4CCW

and seem to be stuck on this error despite pip installing the libraries in the cell above

**"ImportError: Please install the `accelerate` library to use Diffusers with PyTorch. You can do so by running `pip install diffusers[torch]`. Or if torch is already installed, you can run `pip install accelerate`."**
![Screenshot 2022-11-03 at 1 27 16 PM](https://user-images.githubusercontent.com/8299248/199827155-ede789f2-c4bf-4c98-adbe-c10120273ef9.jpg)

**Comment by Toan-Do** [comment]
Hi @Andreilys , thanks for reporting the bug. In the mean time, you can restart the notebook after installing accelerate then rerun the cell 4 (on your image) then it will work. We will fix it soon in our StochasticX library.
