### ISSUE TITLE
tensorrt conversion fails

### ISSUE THREAD

**Issue by harishprabhala** [stochasticai/x-stable-diffusion#19]
Hi. I am trying to convert my onnx file to Tensorrt using the conver_unet_to_tensorrt.py. But i get the below error

```
Traceback (most recent call last):
  File "convert_unet_to_tensorrt.py", line 52, in <module>
    convert(args)
  File "convert_unet_to_tensorrt.py", line 47, in convert
    f.write(serialized_engine)
TypeError: a bytes-like object is required, not 'NoneType' 
```

Except for the onnx file mentioned in the library, none of the other onnx files seem to convert. Any fix? Thanks.

**Comment by Toan-Do** [comment]
Hi @harishprabhala, are you using Tensorrt 8.4.2.2.4? Our code requires TensorRT 8.4.2.2.4 to run.

**Comment by harishprabhala** [comment]
I am using 8.4.1.5. I'll update it to the new version and try again. Will keep you posted.

**Comment by harishprabhala** [comment]
I have tried it in 8.4.2 and I get the following error in demo.py

![WhatsApp Image 2022-11-10 at 5 40 56 PM](https://user-images.githubusercontent.com/26444096/201088418-7646c636-997f-47a9-876b-cfcc4c9165df.jpeg)

**Comment by harishprabhala** [comment]
If I comment out the line 144, the denoising isn't happening and this is the output of the demo.py output

![WhatsApp Image 2022-11-10 at 4 23 11 PM](https://user-images.githubusercontent.com/26444096/201088700-f39d2137-21ca-42e8-8de9-229195e38bca.jpeg)

**Comment by Toan-Do** [comment]
@harishprabhala  It seems that the conversion on your environment did work well. How about trying on google colab : https://github.com/stochasticai/x-stable-diffusion/blob/main/TensorRT/Notebook.ipynb

**Comment by harishprabhala** [comment]
> @harishprabhala It seems that the conversion on your environment did work well. How about trying on google colab : https://github.com/stochasticai/x-stable-diffusion/blob/main/TensorRT/Notebook.ipynb

So, if the conversion went well, why are the predictions turning out this way? Re Colab, how will it be different? Colab has its own set of issues. The Git clone doesn't work properly and there's no terminal access. Any way we can fix it in a local environment? I am testing it on a 2080Ti GPU.

**Comment by Toan-Do** [comment]
We did not test on 2080ti GPU. We tested on a100 and T4 gpu. Google colab has t4 gpu and thus we suggest testing on google colab or on machines which have a100 or T4 gpu.

**Comment by harishprabhala** [comment]
This is the output now on T4. This is becoming impossible 😅

![download](https://user-images.githubusercontent.com/26444096/201332616-8c5c4f9a-e210-4984-ae31-e64447ff510c.png)

**Comment by Toan-Do** [comment]
Hi @harishprabhala , sorry for late response. We have just tested TensorRT code again on Google Colab and it works without any issue. Our tested notebook here: [link](https://colab.research.google.com/drive/1MAwk-DAngujQTaYh1eFZoOuocOhiKsge?usp=sharing). If you are still interested in, please test it again and let us know if any issue. Thank you.

**Comment by ClementCJ** [comment]
@Toan-Do The output on my local T4 is like this
![image_generated](https://user-images.githubusercontent.com/23275206/209809589-9e01bfb2-3b40-42b8-8dfe-381ed8b82771.png)

I also ran it on Google Colab , but it says the following error.
NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968

**Comment by Toan-Do** [comment]
@ClementCJ On Google Colab, after converting model, you should restart the runtime and run start running from this line: https://colab.research.google.com/drive/1MAwk-DAngujQTaYh1eFZoOuocOhiKsge?usp=sharing#scrollTo=hLt_F8vpVGjl
